CREATE DATABASE QLMB

CREATE TABLE CHUYENBAY(
MaCB VARCHAR(10) NOT NULL  PRIMARY KEY, 
GaDi NVARCHAR(10) NOT NULL, 
GaDen NVARCHAR(10) NOT NULL, 
DoDai int, 
GioDi TIME, 
GioDen TIME, 
ChiPhi INT CHECK (ChiPhi BETWEEN 100 AND 1000)
)

CREATE TABLE MAYBAY(
MaCB VARCHAR(10) NOT NULl,
MaMB  VARCHAR(10) NOT NULL PRIMARY KEY, 
Hieu VARCHAR(10), 
TamBay INT
)

CREATE TABLE NHANVIEN(
MaNV VARCHAR(10) NOT NULL PRIMARY KEY, 
Ten NVARCHAR(30), 
Luong INT CHECK(Luong BETWEEN 100 AND 300)
)

CREATE TABLE CHUNGNHAN(
MaNV VARCHAR(10) NOT NULL , 
MaMB VARCHAR(10) NOT NULL 
)
 
ALTER TABLE dbo.CHUNGNHAN ADD CONSTRAINT r1 FOREIGN KEY (MaNV)REFERENCES dbo.NHANVIEN(MaNV)
ALTER TABLE dbo.CHUNGNHAN ADD CONSTRAINT r2 FOREIGN KEY (MaMB)REFERENCES dbo.MAYBAY(MaMB)
ALTER TABLE dbo.MAYBAY ADD CONSTRAINT r3 FOREIGN KEY (MaCB)REFERENCES dbo.CHUYENBAY(MaCB)
